name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Adjust this to your version of PHP

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --optimize-autoloader -vvv
          # Create .env file from .env.example if it does not exist
          if [ ! -f .env ]; then
            cp .env.example .env
          fi
          php artisan key:generate

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$EC2_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST 'bash -s' < ./deploy.sh
